#!mainFile "main.opy"
PRESET_MAP_DATA

rule "Map 1 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 2 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 3 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 4 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 5 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 6 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 7 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 8 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 9 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter

rule "Map 10 Data <--- Insert Map Data Here":
    # Paste your map data here and change the condition to the correct map.
    @Condition getCurrentMap() == Map.WORKSHOP_ISLAND
    @Delimiter